name: swivel_secure_authenticator
description: "Swivel Secure Mobile Authenticator - Enterprise-grade multi-factor authentication (MFA) application"
publish_to: 'none'

version: 6.0.12+103

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI and Navigation
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  go_router: ^14.6.2

  # State Management
  provider: ^6.1.2
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1

  # Database and Storage
  sqflite: ^2.4.1
  sqflite_sqlcipher: ^3.1.0
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5
  path: ^1.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  share_plus: ^7.2.1
  crypto: ^3.0.3

  # Network and HTTP
  http: ^1.2.2
  dio: ^5.7.0
  connectivity_plus: ^6.1.0

  # Security and Authentication
  local_auth: ^2.3.0
  encrypt: ^5.0.3
  otp: ^3.1.4
  mobile_scanner: ^5.0.1
  qr_flutter: ^4.1.0

  # Firebase
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.4
  firebase_analytics: ^11.3.4
  firebase_crashlytics: ^4.1.4

  # Device and Platform
  device_info_plus: ^10.1.2
  package_info_plus: ^8.1.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1

  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  json_annotation: ^4.9.0
  xml: ^6.5.0
  lottie: ^3.1.3

  # Root/Jailbreak Detection
  jailbreak_root_detection: ^1.0.0

  # Biometric Authentication
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/lottie/


